### ISSUE TITLE
Gamepad doesn't work on Cubietruck

### ISSUE THREAD

**Issue by actkk2000** [cubieboard/cubieboard.org#2]
I would like to know if there is a gamepad/joypad/game controller that really works on CT with Android...
I have a common USB dualshock gamepad, also tried a Sixaxis PS3, installed USB/BT Joystick Center, and no luck...
Tested on all nand 1.01 versions of http://dl.cubieboard.org/software/a20-cubietruck/android...
I read that with Gamepad IME and joydev.ko file may work, but dont know where to get a compatible one.
Can you please help? If you can compile a joydev.ko file or make an image with gamepad enabled it will be much appreciated.
Thank you.

**Comment by actkk2000** [comment]
Problem solved, thank you...
http://www.cubieforums.com/index.php?topic=1973.msg12702#msg12702

**Comment by tobewalker** [comment]
Thank you for your support
